backend:
  name: ngetichnews
  repo: netichnews
  branch: main # Change to master if your branch is named master

media_folder: "assets/images" # Where your uploaded photos will save
public_folder: "/assets/images"

collections:
  - name: "news"
    label: "Daily News"
    folder: "posts" # It will automatically create a "posts" folder for your news items
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Headline", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["Politics", "World", "National", "Business", "Tech", "Opinion"]}
      - {label: "Featured Photo", name: "image", widget: "image", required: false}
      - {label: "Video Embed Link (Optional)", name: "video", widget: "string", required: false}
      - {label: "Article Body Text", name: "body", widget: "markdown"}
